string_list=("cli\.array_info\[/cli\.array_data\["
             "cli\.volume_info\[/cli\.volume_data\["
	     "cli\.list_array/cli\.array_list"
	     "cli\.unmount_array/cli\.array_unmount"
	     "target_utils\.Spor/target_utils\.spor"
	     "target_utils\.bringupPOR/target_utils\.bringup_npor"
	     "target_utils\.bringupSystem/target_utils\.bringup_system"
	     "target_utils\.bringupDevice/target_utils\.bringup_device"
	     "target_utils\.bringupSubsystem/target_utils\.bringup_subsystem"
	     "target_utils\.bringupArray/target_utils\.bringup_array"
	     "target_utils\.bringupVolume/target_utils\.bringup_volume"
	     "target_utils\.Npor/target_utils\.npor"
	     "target_utils\.deleteAllVolumes/target_utils\.delete_all_volumes"
             "cli\.start_system/cli\.system_start"
             "cli\.stop_system/cli\.system_stop"
             "cli\.setposproperty_system/cli\.system_setproperty"
             "cli\.info_system/cli\.system_info"
             "cli\.reset_devel/cli\.devel_resetmbr"
             "cli\.updateeventwrr_devel/cli\.devel_eventwrr_update"
             "cli\.reseteventwrr_devel/cli\.devel_eventwrr_reset"
             "cli\.list_array/cli\.array_list"
             "cli\.create_array/cli\.array_create"
             "cli\.mount_array/cli\.array_mount"
             "cli\.unmount_array/cli\.array_unmount"
             "cli\.delete_array/cli\.array_delete"
             "cli\.info_array/cli\.array_info"
             "cli\.addspare_array/cli\.array_addspare"
             "cli\.rmspare_array/cli\.array_rmspare"
             "cli\.autocreate_array/cli\.array_autocreate"
             "cli\.replace_drive_array/cli\.array_replace_disk"
             "cli\.rebuild_array/cli\.array_rebuild"
             "cli\.scan_device/cli\.device_scan"
             "cli\.create_device/cli\.device_create"
             "cli\.list_device/cli\.device_list"
             "cli\.smart_device/cli\.device_smart"
             "cli\.smart_log_device/cli\.device_smart_log"
             "cli\.set_log_level_logger/cli\.logger_set_log_level"
             "cli\.get_log_level_logger/cli\.logger_get_log_level"
             "cli\.apply_log_filter/cli\.logger_apply_log_filter"
             "cli\.info_logger/cli\.logger_info"
             "cli\.start_telemetry/cli\.telemetry_start"
             "cli\.stop_telemetry/cli\.telemetry_stop"
             "cli\.get_property/cli\.telemetry_get_property"
             "cli\.set_property/cli\.telemetry_set_property"
             "cli\.create_volume_policy_qos/cli\.qos_create_volume_policy"
             "cli\.reset_volume_policy_qos/cli\.qos_reset_volume_policy"
             "cli\.list_volume_policy_qos/cli\.qos_list_volume_policy"
             "cli\.list_volume/cli\.volume_list"
             "cli\.info_volume/cli\.volume_info"
             "cli\.create_volume/cli\.volume_create"
             "cli\.delete_volume/cli\.volume_delete"
             "cli\.mount_volume/cli\.volume_mount"
             "cli\.rename_volume/cli\.volume_rename"
             "cli\.unmount_volume/cli\.volume_unmount"
             "cli\.mount_with_subsystem_volume/cli\.volume_mount_with_subsystem"
             "cli\.create_subsystem/cli\.subsystem_create"
             "cli\.list_subsystem/cli\.subsystem_list"
             "cli\.add_listner_subsystem/cli\.subsystem_add_listner"
             "cli\.create_transport_subsystem/cli\.subsystem_create_transport"
	     "cli\.delete_subsystem/cli\.subsystem_delete")

file_names=("lib/*.py" "lib/*/*.py" "utils/*.py" "testcase/*.py" "testcase/*/*.py" "testcase/*/*/*.py")

for file_name in ${file_names[@]}
do
	for string in ${string_list[@]}
	do
		sed -i "s/$string/g" $file_name 
	done
done


